apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-ace-rest-cp4i-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ace/environments/cp4i
    repoURL: https://github.com/xcel-demo/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
